# Generated by Django 5.1.5 on 2025-03-08 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0008_remove_rentalroom_is_active_and_more'),
        ('save_for_later', '0003_saveforlater___save_for_later__rental_room_renter__unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveforlater',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='saveforlater',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
