# Generated by Django 5.1.5 on 2025-03-13 17:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRoomHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_room_history', to='rental_room.rentalroom')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_room_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
