# Generated by Django 5.1.5 on 2025-03-04 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_room', '0004_remove_electricitywaterchargeslist_rental_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRoomHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_room_history', to='rental_room.rentalroom')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_room_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
