# Generated by Django 5.1.5 on 2025-03-06 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_room_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchroomhistory',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
