# Generated by Django 5.1.5 on 2025-03-12 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_room_history', '0002_searchroomhistory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchroomhistory',
            name='weight',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
