# Generated by Django 5.1.5 on 2025-02-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_initial'),
        ('rental_room', '0004_alter_rentalroomimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distances', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distances', to=settings.AUTH_USER_MODEL),
        ),
    ]
