# Generated by Django 5.1.5 on 2025-03-06 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_initial'),
        ('rental_room', '0007_monthlychargesdetails_is_settled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='distance',
            constraint=models.UniqueConstraint(fields=('rental_room', 'renter'), name='__DISTANCE__rental_room_renter__unique_together'),
        ),
    ]
