# Generated by Django 5.1.5 on 2025-03-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0004_distance___distance__rental_room_renter__unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='duration_in_minutes',
        ),
    ]
