# Generated by Django 5.1.5 on 2025-03-11 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0005_remove_distance_duration_in_minutes'),
        ('rental_room', '0008_remove_rentalroom_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to=settings.AUTH_USER_MODEL),
        ),
    ]
