# Generated by Django 5.1.5 on 2025-03-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('rental_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='rental_room.rentalroom'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rented_contracts', to='contract.contract'),
        ),
    ]
