# Generated by Django 5.1.5 on 2025-02-05 16:31

import apps.rental_room.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_charge_type', models.CharField(choices=[('unit', '/kWh'), ('person', '/người')], default='unit', max_length=8)),
                ('electricity_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_charge_type', models.CharField(choices=[('unit', '/m3'), ('person', '/người')], default='unit', max_length=8)),
                ('water_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('wifi_charge', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rubbish_charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RentalRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('additional_address', models.TextField(max_length=512)),
                ('closing_time', models.TimeField(null=True)),
                ('max_occupancy_per_room', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('empty_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('further_description', models.TextField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.rental_room.models.rental_room_image_upload_to)),
            ],
        ),
    ]
