# Generated by Django 5.1.5 on 2025-02-10 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalroom',
            name='lessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessed_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges_list', to='rental_room.rentalroom'),
        ),
        migrations.AddField(
            model_name='electricitywaterchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_water_charges_list', to='rental_room.rentalroom'),
        ),
        migrations.AddField(
            model_name='rentalroomimage',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_room.rentalroom'),
        ),
        migrations.AddField(
            model_name='roomchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_charges_list', to='rental_room.rentalroom'),
        ),
        migrations.AddConstraint(
            model_name='rentalroom',
            constraint=models.CheckConstraint(condition=models.Q(('empty_number__lte', models.F('total_number'))), name='__RENTAL_ROOM__empty_number__lte__total_number'),
        ),
        migrations.AddConstraint(
            model_name='otherchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__OTHER_CHARGES_LIST__end_date__gt__start_date'),
        ),
        migrations.AddConstraint(
            model_name='electricitywaterchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__ELECTRICITY_WATER_CHARGES_LIST__end_date__gt__start_date'),
        ),
        migrations.AddConstraint(
            model_name='roomchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('deposit__lte', models.F('room_charge'))), name='__ROOM_CHARGES_LIST__deposit__lte__room_charge'),
        ),
        migrations.AddConstraint(
            model_name='roomchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__ROOM_CHARGES_LIST__end_date__gt__start_date'),
        ),
    ]
