# Generated by Django 5.1.5 on 2025-02-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('rental_room', '0001_initial'),
        ('user_account_app_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalroom',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_rooms', to='user_account_app_label.manager'),
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_rooms', to='address.commune'),
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='possessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessed_rooms', to='user_account_app_label.lessor'),
        ),
        migrations.AddField(
            model_name='chargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='rental_room.rentalroom'),
        ),
        migrations.AddField(
            model_name='rentalroomimage',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_room.rentalroom'),
        ),
        migrations.AddConstraint(
            model_name='rentalroom',
            constraint=models.CheckConstraint(condition=models.Q(('empty_number__lte', models.F('total_number'))), name='__RENTAL_ROOM__empty_number__lte__total_number'),
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('deposit__lte', models.F('room_charge'))), name='__CHARGES_LIST__deposit__lte__room_charge'),
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__CHARGES_LIST__end_date__gt__start_date'),
        ),
    ]
