# Generated by Django 5.1.5 on 2025-03-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargeslist',
            name='__CHARGES_LIST__deposit__lte__room_charge',
        ),
    ]
