# Generated by Django 5.1.5 on 2025-02-08 17:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityWaterChargesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('electricity_charge_type', models.CharField(choices=[('unit', '/kWh'), ('person', '/người')], default='unit', max_length=8)),
                ('electricity_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_charge_type', models.CharField(choices=[('unit', '/m3'), ('person', '/người')], default='unit', max_length=8)),
                ('water_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_water_charges_list', to='rental_room.rentalroom')),
            ],
        ),
        migrations.CreateModel(
            name='OtherChargesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wifi_charge', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rubbish_charge', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_charges_list', to='rental_room.rentalroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomChargesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_charges_list', to='rental_room.rentalroom')),
            ],
        ),
        migrations.DeleteModel(
            name='ChargesList',
        ),
        migrations.AddConstraint(
            model_name='electricitywaterchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__ELECTRICITY_WATER_CHARGES_LIST__end_date__gt__start_date'),
        ),
        migrations.AddConstraint(
            model_name='otherchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__OTHER_CHARGES_LIST__end_date__gt__start_date'),
        ),
        migrations.AddConstraint(
            model_name='roomchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('deposit__lte', models.F('room_charge'))), name='__ROOM_CHARGES_LIST__deposit__lte__room_charge'),
        ),
        migrations.AddConstraint(
            model_name='roomchargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__ROOM_CHARGES_LIST__end_date__gt__start_date'),
        ),
    ]
