# Generated by Django 5.1.5 on 2025-02-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalroom',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
