# Generated by Django 5.1.5 on 2025-03-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0002_remove_chargeslist___charges_list__deposit__lte__room_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlychargesdetails',
            old_name='due_charges',
            new_name='due_charge',
        ),
        migrations.RenameField(
            model_name='monthlychargesdetails',
            old_name='paid_charges',
            new_name='paid_charge',
        ),
        migrations.RenameField(
            model_name='monthlychargesdetails',
            old_name='prev_remaining_charges',
            new_name='prev_remaining_charge',
        ),
    ]
