# Generated by Django 5.1.5 on 2025-03-04 12:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitywaterchargeslist',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='electricitywaterchargeslist',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='otherchargeslist',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='otherchargeslist',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomchargeslist',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomchargeslist',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='MonitoringRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=20)),
                ('remaining_charges_prev_month', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_charges_in_month', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_charges_in_month', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_rentals', to='rental_room.rentalroom')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rented_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
