# Generated by Django 5.1.5 on 2025-03-16 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0003_rename_due_charges_monthlychargesdetails_due_charge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monitoringrental',
            name='__MONITORING_RENTAL__end_date__gte__start_date_or_null',
        ),
        migrations.AddConstraint(
            model_name='monitoringrental',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='__MONITORING_RENTAL__end_date__gt__start_date_or_null'),
        ),
    ]
