# Generated by Django 5.1.5 on 2025-03-04 14:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0003_alter_electricitywaterchargeslist_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitywaterchargeslist',
            name='rental_room',
        ),
        migrations.RemoveField(
            model_name='otherchargeslist',
            name='rental_room',
        ),
        migrations.RemoveField(
            model_name='roomchargeslist',
            name='rental_room',
        ),
        migrations.RemoveField(
            model_name='monitoringrental',
            name='due_charges_in_month',
        ),
        migrations.RemoveField(
            model_name='monitoringrental',
            name='paid_charges_in_month',
        ),
        migrations.RemoveField(
            model_name='monitoringrental',
            name='remaining_charges_prev_month',
        ),
        migrations.RemoveField(
            model_name='monitoringrental',
            name='rental_room',
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChargesList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('wifi_charge', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('rubbish_charge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_lists', to='rental_room.rentalroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=10)),
                ('rental_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_codes', to='rental_room.rentalroom')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyChargesDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kwhNumber', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('m3Number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('prev_remaining_charges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_charges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_charges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_charges_details', to='rental_room.roomcode')),
            ],
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='room_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_rentals', to='rental_room.roomcode'),
        ),
        migrations.AddConstraint(
            model_name='monitoringrental',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='__MONITORING_RENTAL__end_date__gt__start_date'),
        ),
        migrations.DeleteModel(
            name='ElectricityWaterChargesList',
        ),
        migrations.DeleteModel(
            name='OtherChargesList',
        ),
        migrations.DeleteModel(
            name='RoomChargesList',
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('deposit__lte', models.F('room_charge'))), name='__CHARGES_LIST__deposit__lte__room_charge'),
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date')), ('end_date__isnull', True), _connector='OR'), name='__CHARGES_LIST__end_date__gt__start_date'),
        ),
    ]
