# Generated by Django 5.1.5 on 2025-03-04 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0004_remove_electricitywaterchargeslist_rental_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlychargesdetails',
            old_name='kwhNumber',
            new_name='new_kWh_reading',
        ),
        migrations.RenameField(
            model_name='monthlychargesdetails',
            old_name='m3Number',
            new_name='new_m3_reading',
        ),
        migrations.AddField(
            model_name='monthlychargesdetails',
            name='old_kWh_reading',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='monthlychargesdetails',
            name='old_m3_reading',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='monthlychargesdetails',
            constraint=models.CheckConstraint(condition=models.Q(('new_kWh_reading__lte', models.F('old_kWh_reading'))), name='__MONTHLY_CHARGES_DETAILS__new_kWh_reading__lte__old_kWh_reading'),
        ),
        migrations.AddConstraint(
            model_name='monthlychargesdetails',
            constraint=models.CheckConstraint(condition=models.Q(('new_m3_reading__lte', models.F('old_m3_reading'))), name='__MONTHLY_CHARGES_DETAILS__new_m3_reading__lte__old_m3_reading'),
        ),
    ]
