# Generated by Django 5.1.5 on 2025-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0004_remove_monitoringrental___monitoring_rental__end_date__gte__start_date_or_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargeslist',
            name='__CHARGES_LIST__end_date__gte__start_date_or_null',
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='__CHARGES_LIST__end_date__gt__start_date_or_null'),
        ),
    ]
