# Generated by Django 5.1.5 on 2025-02-27 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_commune_district_alter_district_province'),
        ('rental_room', '0004_alter_rentalroomimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitywaterchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electricity_water_charges_list', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='otherchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_charges_list', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_rooms', to='address.commune'),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='lessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='possessed_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalroomimage',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='rental_room.rentalroom'),
        ),
        migrations.AlterField(
            model_name='roomchargeslist',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_charges_list', to='rental_room.rentalroom'),
        ),
    ]
