# Generated by Django 5.1.5 on 2025-03-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0005_alter_electricitywaterchargeslist_rental_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitywaterchargeslist',
            name='electricity_charge_type',
            field=models.CharField(choices=[('UNIT', '/kWh'), ('PERSON', '/người')], default='UNIT', max_length=8),
        ),
        migrations.AlterField(
            model_name='electricitywaterchargeslist',
            name='water_charge_type',
            field=models.CharField(choices=[('UNIT', '/m3'), ('PERSON', '/người')], default='UNIT', max_length=8),
        ),
    ]
