# Generated by Django 5.1.5 on 2025-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0005_rename_kwhnumber_monthlychargesdetails_new_kwh_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalroom',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalroom',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
