# Generated by Django 5.1.5 on 2025-03-16 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0005_remove_chargeslist___charges_list__end_date__gte__start_date_or_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomcode',
            name='__ROOM_CODE__remaining_occupancy__lte__max_occupancy',
        ),
        migrations.RemoveField(
            model_name='roomcode',
            name='remaining_occupancy',
        ),
        migrations.AddField(
            model_name='roomcode',
            name='current_occupancy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='roomcode',
            constraint=models.CheckConstraint(condition=models.Q(('current_occupancy__lte', models.F('max_occupancy'))), name='__ROOM_CODE__current_occupancy__lte__max_occupancy'),
        ),
    ]
