# Generated by Django 5.1.5 on 2025-03-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0006_remove_roomcode___room_code__remaining_occupancy__lte__max_occupancy_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlychargesdetails',
            name='__MONTHLY_CHARGES_DETAILS__new_kWh_reading__lte__old_kWh_reading',
        ),
        migrations.RemoveConstraint(
            model_name='monthlychargesdetails',
            name='__MONTHLY_CHARGES_DETAILS__new_m3_reading__lte__old_m3_reading',
        ),
        migrations.AddField(
            model_name='monthlychargesdetails',
            name='continue_renting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='monthlychargesdetails',
            constraint=models.CheckConstraint(condition=models.Q(('new_kWh_reading__gte', models.F('old_kWh_reading'))), name='__MONTHLY_CHARGES_DETAILS__new_kWh_reading__gte__old_kWh_reading'),
        ),
        migrations.AddConstraint(
            model_name='monthlychargesdetails',
            constraint=models.CheckConstraint(condition=models.Q(('new_m3_reading__gte', models.F('old_m3_reading'))), name='__MONTHLY_CHARGES_DETAILS__new_m3_reading__gte__old_m3_reading'),
        ),
    ]
