# Generated by Django 5.1.5 on 2025-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0006_rentalroom_latitude_rentalroom_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlychargesdetails',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
