# Generated by Django 5.1.5 on 2025-03-08 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0007_monthlychargesdetails_is_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalroom',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='rentalroom',
            name='average_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
