# Generated by Django 5.1.5 on 2025-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0007_remove_monthlychargesdetails___monthly_charges_details__new_kwh_reading__lte__old_kwh_reading_and_mo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChargesList',
            new_name='Charges',
        ),
        migrations.RenameModel(
            old_name='MonthlyChargesDetails',
            new_name='MonthlyRoomInvoice',
        ),
        migrations.RenameModel(
            old_name='RentalRoomImage',
            new_name='RoomImage',
        ),
        migrations.RemoveConstraint(
            model_name='charges',
            name='__CHARGES_LIST__end_date__gt__start_date_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='monthlyroominvoice',
            name='__MONTHLY_CHARGES_DETAILS__new_kWh_reading__gte__old_kWh_reading',
        ),
        migrations.RemoveConstraint(
            model_name='monthlyroominvoice',
            name='__MONTHLY_CHARGES_DETAILS__new_m3_reading__gte__old_m3_reading',
        ),
        migrations.AddConstraint(
            model_name='charges',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='__CHARGES__end_date__gt__start_date_or_null'),
        ),
        migrations.AddConstraint(
            model_name='monthlyroominvoice',
            constraint=models.CheckConstraint(condition=models.Q(('new_kWh_reading__gte', models.F('old_kWh_reading'))), name='__MONTHLY_ROOM_INVOICE__new_kWh_reading__gte__old_kWh_reading'),
        ),
        migrations.AddConstraint(
            model_name='monthlyroominvoice',
            constraint=models.CheckConstraint(condition=models.Q(('new_m3_reading__gte', models.F('old_m3_reading'))), name='__MONTHLY_ROOM_INVOICE__new_m3_reading__gte__old_m3_reading'),
        ),
    ]
