# Generated by Django 5.1.5 on 2025-03-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0008_rename_chargeslist_charges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcode',
            old_name='is_sharable',
            new_name='is_shared',
        ),
    ]
