# Generated by Django 5.1.5 on 2025-03-12 08:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0008_remove_rentalroom_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargeslist',
            name='__CHARGES_LIST__end_date__gt__start_date',
        ),
        migrations.RemoveConstraint(
            model_name='monitoringrental',
            name='__MONITORING_RENTAL__end_date__gt__start_date',
        ),
        migrations.AlterField(
            model_name='chargeslist',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
        migrations.AlterField(
            model_name='chargeslist',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', datetime.date(2025, 3, 12))), name='__CHARGES_LIST__start_date__gte__today'),
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__CHARGES_LIST__end_date__gt__start_date'),
        ),
        migrations.AddConstraint(
            model_name='monitoringrental',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', datetime.date(2025, 3, 12))), name='__MONITORING_RENTAL__start_date__gte__today'),
        ),
        migrations.AddConstraint(
            model_name='monitoringrental',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='__MONITORING_RENTAL__end_date__gt__start_date'),
        ),
    ]
