# Generated by Django 5.1.5 on 2025-03-12 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0009_remove_chargeslist___charges_list__end_date__gt__start_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargeslist',
            name='__CHARGES_LIST__start_date__gte__today',
        ),
        migrations.RemoveConstraint(
            model_name='monitoringrental',
            name='__MONITORING_RENTAL__start_date__gte__today',
        ),
        migrations.AlterField(
            model_name='chargeslist',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chargeslist',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monitoringrental',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
