# Generated by Django 5.1.5 on 2025-03-20 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0010_alter_monitoringrental_renter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='rental_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='rental_room.rentalroom'),
        ),
    ]
