# Generated by Django 5.1.5 on 2025-03-12 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_room', '0010_remove_chargeslist___charges_list__start_date__gte__today_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chargeslist',
            name='__CHARGES_LIST__end_date__gt__start_date',
        ),
        migrations.RemoveConstraint(
            model_name='monitoringrental',
            name='__MONITORING_RENTAL__end_date__gt__start_date',
        ),
        migrations.AddConstraint(
            model_name='chargeslist',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='__CHARGES_LIST__end_date__gte__start_date'),
        ),
        migrations.AddConstraint(
            model_name='monitoringrental',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='__MONITORING_RENTAL__end_date__gte__start_date'),
        ),
    ]
