# Generated by Django 5.1.5 on 2025-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGER', 'Quản lý'), ('LESSOR', 'Chủ trọ'), ('RENTER', 'Người thuê')], max_length=10),
        ),
    ]
