# Generated by Django 5.1.5 on 2025-02-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Quản trị viên'), ('M', 'Quản lý'), ('L', 'Người cho thuê'), ('R', 'Người thuê')], max_length=1),
        ),
    ]
