# Generated by Django 5.1.5 on 2025-02-26 15:11

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
