# Generated by Django 5.1.5 on 2025-03-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0003_customuser_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_balance',
        ),
    ]
