# Generated by Django 5.1.5 on 2025-02-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_commune_district_alter_district_province'),
        ('user_account_app_label', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='workplace_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='working_renters', to='address.commune'),
        ),
    ]
