# Generated by Django 5.1.5 on 2025-03-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0005_alter_customuser_workplace_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('UNKNOWN', 'Không rõ')], default='MALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGER', 'Quản lý'), ('LESSOR', 'Người cho thuê'), ('RENTER', 'Người thuê')], max_length=10),
        ),
    ]
