# Generated by Django 5.1.5 on 2025-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account_app_label', '0005_customuser_workplace_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGER', 'Quản lý'), ('LESSOR', 'Chủ trọ'), ('RENTER', 'Người thuê')], default='RENTER', max_length=10),
        ),
    ]
